### ISSUE TITLE
Feature Request - Hide the status bar

### ISSUE THREAD

**Issue by hcal** [TsFreddie/EssentialLayoutWhitelist#1]
Essential Layout is a great app.  Hiding the navigation bar somehow really changes the feel of the device.  I was wondering if it would be possible to add a feature to hide the status bar in certain apps similar to the way you remove the navigation bar.  

For and example, there is an app called "Fullscreen Immersive" in the play store that removes the navbar.  Fullscreen Immersive only has a system wide setting (as opposed to app by app like you program) and for some reason disables the keyboard.  When it works it looks great but generally it doesn't work well on the PH1 or Essential Layout.  

BTW,  I appreciate your app the way it is.  I just wanted to share an idea.

**Comment by TsFreddie** [comment]
I'll see what I can do.
